### ISSUE TITLE
question: Having trouble getting my app to use the customerKey for the product rather than the remote proxy when deployed to Apigee ....

### ISSUE THREAD

**Issue by emcpadden** [apigee-127/a127-documentation#10]
I am having trouble getting apikey security to work when deployed to Apigee.  

I have it working using a remote proxy on my machine using the customerKey in APigee for my remote proxy.

When I deploy to Apigee, the apikey security still works if I use the customerKey for my remote proxy.  I am confused as how to configure things so that it will use the customerKey for a product that contains my API (instead of the remote proxy customerKey).

Here is what is in my swagger file for x-a127-config and x-a127-service:
```yaml
x-a127-config: 
  remote.key: &apigeeProxyKey CONFIGURED
  remote.uri: &apigeeProxyUri CONFIGURED
  oauthProvider: &oauthProvider CONFIGURED
  synergyUri: &synergyUri CONFIGURED
  synergyApiKey: &synergyApiKey CONFIGURED
x-a127-services: 
  apiKeyHeaderSecurity:
    provider: *oauthProvider
    options:
      uri: *apigeeProxyUri
      key: *apigeeProxyKey 
  apiKeyQuerySecurity:
    provider: *oauthProvider
    options:
      uri: *apigeeProxyUri
      key: *apigeeProxyKey 
```

Please let me know if there is anything else I should be telling you about my code.

Is there some other configuration that I need to do to get my app to use the customerKey defined for the app when it is deployed to Apigee?

Thanks for your help,
...Ed
